project:
  type: website

website:
  title: "Jefferson Suh"
  navbar:
    background: none
    search: false
    left:
      - text: writing
        href: writing.html
      - text: about
        href: about.html
      - text: links
        href: links.html
      - text: contact
        href: contact.html
  page-footer:
    right: |
      Â© 2025 Jefferson Suh / Los Angeles

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    mainfont: "Times New Roman"